# Permalinks
permalink:           pretty

# Setup
title:               Name
tagline:             A computer music blog
description:         >
  Some tagline. Fix me in the future.
url:                 https://bh90210.github.io
paginate:            5
baseurl:             ""

# Assets
sass:
  style:            compressed

# About/contact
author:
  name:              Byron Christodoulou
  url:               https://bh90210.github.io
  email:             ktc@protonmail.ch

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/bh90210/mlsic

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
