# User config
author: "DIGIGREENCORP LTD"
tagline: "Delivering C  O  R  P  O  R  A  T  E™ software since 2020."
description: "Delivering C&nbsp;&nbsp;O&nbsp;&nbsp;R&nbsp;&nbsp;P&nbsp;&nbsp;O&nbsp;&nbsp;R&nbsp;&nbsp;A&nbsp;&nbsp;T&nbsp;&nbsp;E™ software since 2020."
keywords: "digi, green, corp"
email: "info@digigreencorp.ltd"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
# github: "https://github.com/"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
